/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.inventory.ui.setup.dialog;

import com.common.Global;
import com.common.TableCellRender;
import com.inventory.entity.StockUnit;
import com.inventory.ui.setup.dialog.common.StockUnitChooserTableModel;
import com.inventory.ui.setup.dialog.common.StockUnitTableModel;
import java.awt.Dialog;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import lombok.Getter;
import lombok.Setter;

/**
 *
 * @author Lenovo
 */
public class StockUnitChooserDialog extends javax.swing.JDialog {

    private final StockUnitChooserTableModel tableModel = new StockUnitChooserTableModel();
    @Getter
    @Setter
    private String selectUnit;

    /**
     * Creates new form StockUnitChooser
     *
     * @param frame
     */
    public StockUnitChooserDialog(JFrame frame) {
        super(frame, Dialog.ModalityType.APPLICATION_MODAL);
        setUndecorated(true);
        initComponents();
        initTable();
    }

    private void initTable() {
        tblUnit.setModel(tableModel);
        tblUnit.getTableHeader().setFont(Global.tblHeaderFont);
        tblUnit.setFont(Global.textFont);
        tblUnit.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUnit.setRowHeight(Global.tblRowHeight);
        tblUnit.setDefaultRenderer(Object.class, new TableCellRender());
        KeyStroke enter = KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0);
        tblUnit.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(enter, "enter");
        tblUnit.getActionMap().put("enter", new EnterAction());
    }

    private class EnterAction extends AbstractAction {

        @Override
        public void actionPerformed(ActionEvent e) {
            int row = tblUnit.getSelectedRow();
            setSelectUnit(tableModel.getStockUnit(row).getKey().getUnitCode());
            dispose();
        }
    }

    public void setListUnit(List<StockUnit> list) {
        tableModel.setListUnit(list);
        tblUnit.setRowSelectionInterval(0, 0);
        tblUnit.requestFocus();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUnit = new javax.swing.JTable();

        tblUnit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUnit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUnit;
    // End of variables declaration//GEN-END:variables
}
