/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.user.setup;

import com.repo.AccountRepo;
import com.acc.common.BusinessTypeComboBoxModel;
import com.acc.model.BusinessType;
import com.acc.setup.COATemplateSetup;
import com.common.Global;
import com.common.SelectionObserver;
import com.repo.InventoryRepo;
import com.repo.UserRepo;
import com.user.dialog.BusinessTypeSetupDialog;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author Lenovo
 */
@Component
public class CompanyTemplate extends javax.swing.JPanel {

    @Autowired
    private UserRepo userRepo;
    @Autowired
    private InventoryRepo inventoryRepo;
    @Autowired
    private AccountRepo accountRepo;
    private SelectionObserver observer;
    private JProgressBar progress;
    private BusinessTypeSetupDialog dialog;
    private BusinessTypeComboBoxModel businessTypeComboBoxModel;
    private final MenuTemplateSetup menuTemplateSetup = new MenuTemplateSetup();
    private final COATemplateSetup cOATemplateSetup = new COATemplateSetup();

    public SelectionObserver getObserver() {
        return observer;
    }

    public void setObserver(SelectionObserver observer) {
        this.observer = observer;
    }

    public JProgressBar getProgress() {
        return progress;
    }

    public void setProgress(JProgressBar progress) {
        this.progress = progress;
    }

    /**
     * Creates new form SystemTemplate
     */
    public CompanyTemplate() {
        initComponents();
    }

    private void initCombo() {
        cboBusType.setFont(Global.textFont);
        userRepo.getBusinessType().subscribe((t) -> {
            businessTypeComboBoxModel = new BusinessTypeComboBoxModel(t);
            cboBusType.setModel(businessTypeComboBoxModel);
            cboBusType.setSelectedIndex(t.size() - 1);
        });
    }

    private void search() {
        menuTemplateSetup.initMain();
        cOATemplateSetup.initMain();
    }

    public void intTabMain() {
        initCombo();
        tab.add("Menu", getMenuTemplate());
        tab.add("COA", getCOATemplate());
    }

    private JPanel getMenuTemplate() {
        menuTemplateSetup.setBusType(cboBusType);
        menuTemplateSetup.setUserRepo(userRepo);
        menuTemplateSetup.setProgress(progress);
        menuTemplateSetup.setObserver(observer);
        return menuTemplateSetup;
    }

    private JPanel getCOATemplate() {
        cOATemplateSetup.setCboBusType(cboBusType);
        cOATemplateSetup.setAccountRepo(accountRepo);
        cOATemplateSetup.setProgress(progress);
        cOATemplateSetup.setObserver(observer);
        return cOATemplateSetup;
    }

    private void addBusType() {
        if (dialog == null) {
            dialog = new BusinessTypeSetupDialog(Global.parentForm);
            dialog.setIconImage(Global.parentForm.getIconImage());
            dialog.setUserRepo(userRepo);
            dialog.setAccountRepo(accountRepo);
            dialog.setLocationRelativeTo(null);
        }
        dialog.search();
        dialog.setVisible(true);
        initCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        cboBusType = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        tab.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        tab.setFont(Global.menuFont);

        cboBusType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboBusTypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(Global.lableFont);
        jLabel2.setText("Business Type");

        jButton1.setFont(Global.lableFont);
        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboBusType, 0, 280, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cboBusType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tab, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cboBusTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboBusTypeActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_cboBusTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addBusType();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<BusinessType> cboBusType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane tab;
    // End of variables declaration//GEN-END:variables
}
