/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.inventory.ui.system;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import com.inventory.common.Global;
import com.inventory.common.ReturnObject;
import com.inventory.model.SysProperty;
import com.inventory.ui.system.common.SystemPropertyTableModel;
import com.inventory.ui.setup.dialog.common.AutoClearEditor;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Mono;

/**
 *
 * @author Lenovo
 */
@Component
public class SystemProperty extends javax.swing.JPanel {

    @Autowired
    private WebClient webClient;
    private final SystemPropertyTableModel tableModel = new SystemPropertyTableModel();
    private final Gson gson = new GsonBuilder().setDateFormat(DateFormat.FULL, DateFormat.FULL).create();

    /**
     * Creates new form SystemProperty
     */
    public SystemProperty() {
        initComponents();
    }

    public void initTable() {
        tableModel.setWebClient(webClient);
        tblSystem.setModel(tableModel);
        tblSystem.getTableHeader().setFont(Global.tblHeaderFont);
        tblSystem.setRowHeight(Global.tblRowHeight);
        tblSystem.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblSystem.getColumnModel().getColumn(0).setCellEditor(new AutoClearEditor());
        tblSystem.getColumnModel().getColumn(1).setCellEditor(new AutoClearEditor());
        tblSystem.getColumnModel().getColumn(2).setCellEditor(new AutoClearEditor());
        tblSystem.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "selectNextColumnCell");
        searchSysProperty();
    }

    public void searchSysProperty() {
        Mono<ReturnObject> result = webClient.get()
                .uri(builder -> builder.path("/setup/get-system-property")
                .queryParam("compCode", Global.compCode)
                .build())
                .retrieve()
                .bodyToMono(ReturnObject.class);
        result.subscribe((t) -> {
            java.lang.reflect.Type listType = new TypeToken<ArrayList<SysProperty>>() {
            }.getType();
            List<SysProperty> listSys = gson.fromJson(gson.toJsonTree(t.getList()), listType);
            tableModel.setListProperty(listSys);
            tableModel.addNewRow();
            tblSystem.requestFocus();
        }, (e) -> {
            JOptionPane.showMessageDialog(this, e.getMessage());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSystem = new javax.swing.JTable();
        txtFilter = new javax.swing.JTextField();

        tblSystem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblSystem);

        txtFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(txtFilter))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSystem;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
