/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.user.dialog;

import com.common.SelectionObserver;
import com.user.common.VRoleCompanyTableModel;
import com.user.model.CompanyInfo;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.List;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author DELL
 */
@Slf4j
public class CompanyOptionDialog extends javax.swing.JDialog implements SelectionObserver {

    private final VRoleCompanyTableModel companyTableModel = new VRoleCompanyTableModel();
    private SelectionObserver observer;
    private CompanyInfo companyInfo;
    private List<CompanyInfo> listCompany;

    public List<CompanyInfo> getListCompany() {
        return listCompany;
    }

    public void setListCompany(List<CompanyInfo> listCompany) {
        this.listCompany = listCompany;
    }

    public CompanyInfo getCompanyInfo() {
        return companyInfo;
    }

    public void setCompanyInfo(CompanyInfo companyInfo) {
        this.companyInfo = companyInfo;
    }

    public SelectionObserver getObserver() {
        return observer;
    }

    public void setObserver(SelectionObserver observer) {
        this.observer = observer;
    }

    /**
     * Creates new form RoleSetupDialog
     *
     * @param parent
     */
    public CompanyOptionDialog(JFrame parent) {
        super(parent, true);
        initComponents();
    }

    public void initMain() {
        panelCompany.setLayout(new BoxLayout(panelCompany, BoxLayout.Y_AXIS));
        companyTableModel.setListCompany(listCompany);
        listCompany.forEach((t) -> {
            JPanel companyPanel = getCompanyPanel(t);
            companyPanel.setMaximumSize(new Dimension(Short.MAX_VALUE, companyPanel.getPreferredSize().height));
            panelCompany.add(companyPanel);
        });
        JScrollPane scrollPane = new JScrollPane(panelCompany);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        this.setLayout(new BorderLayout());
        this.add(scrollPane, BorderLayout.CENTER);
        this.revalidate();
        this.repaint();
    }

    private JPanel getCompanyPanel(CompanyInfo info) {
        CompanyPanel companyPanel = new CompanyPanel(info);
        companyPanel.setObserver(this);
        return companyPanel;
    }

    public int getCompanyPanelIndex(JPanel companyPanel) {
        int index = panelCompany.getComponentZOrder(companyPanel);
        return index;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCompany = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Company List");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panelCompany.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout panelCompanyLayout = new javax.swing.GroupLayout(panelCompany);
        panelCompany.setLayout(panelCompanyLayout);
        panelCompanyLayout.setHorizontalGroup(
            panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        panelCompanyLayout.setVerticalGroup(
            panelCompanyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCompany, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelCompany;
    // End of variables declaration//GEN-END:variables

    @Override
    public void selected(Object source, Object selectObj) {
        if (source.toString().endsWith("select")) {
            if (selectObj instanceof CompanyInfo v) {
                companyInfo = v;
                this.dispose();
            }
        }
    }
}
