/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.user.dialog;

import com.common.Global;
import com.common.ProUtil;
import com.common.SelectionObserver;
import com.common.Util1;
import com.user.model.PropertyKey;
import com.user.model.SysProperty;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class ReportNameDialog extends javax.swing.JDialog {

    private SelectionObserver observer;

    public void setObserver(SelectionObserver observer) {
        this.observer = observer;
    }

    private final ActionListener action = (ActionEvent e) -> {
        if (e.getSource() instanceof JCheckBox chk) {
            String key = chk.getName();
            String value = Util1.getString(chk.isSelected());
            SysProperty p = new SysProperty();
            PropertyKey pKey = new PropertyKey();
            pKey.setPropKey(key);
            p.setKey(pKey);
            p.setPropValue(value);
            save(p);
        }
        if (e.getSource() instanceof JTextField txt) {
            String key = txt.getName();
            String value = txt.getText();
            SysProperty p = new SysProperty();
            PropertyKey pKey = new PropertyKey();
            pKey.setPropKey(key);
            p.setKey(pKey);
            p.setPropValue(value);
            save(p);
        }
    };

    /**
     * Creates new form ReportNameDialog
     *
     * @param frame
     */
    public ReportNameDialog(JFrame frame) {
        super(frame, false);
        initComponents();
        initTextBox();
    }

    private void initTextBox() {
        txtIOVoucher.setName(ProUtil.STOCK_IO_VOUCHER);
        txtIOVoucher.addActionListener(action);
        txtTranVoucher.setName(ProUtil.TRANSFER_VOUCHER);
        txtTranVoucher.addActionListener(action);
        txtPurVou.setName(ProUtil.PURCHASE_VOUCHER);
        txtPurVou.addActionListener(action);
    }

    public void setData(HashMap<String, String> hmProperty) {
        txtIOVoucher.setText(hmProperty.get(txtIOVoucher.getName()));
        txtTranVoucher.setText(hmProperty.get(txtTranVoucher.getName()));
        txtPurVou.setText(hmProperty.get(txtPurVou.getName()));
    }

    private void save(SysProperty p) {
        int yn = JOptionPane.showConfirmDialog(this, "Are you sure to change setting?", "Setting", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (yn == JOptionPane.YES_OPTION) {
            observer.selected("save", p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTranVoucher = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtIOVoucher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPurVou = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("Transfer Voucher");

        txtTranVoucher.setFont(Global.textFont);

        jLabel2.setFont(Global.lableFont);
        jLabel2.setText("Stock I/O Voucher");

        txtIOVoucher.setFont(Global.textFont);

        jLabel3.setFont(Global.lableFont);
        jLabel3.setText("Purchase Voucher");

        txtPurVou.setFont(Global.textFont);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTranVoucher)
                    .addComponent(txtIOVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                    .addComponent(txtPurVou, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTranVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIOVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPurVou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(353, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIOVoucher;
    private javax.swing.JTextField txtPurVou;
    private javax.swing.JTextField txtTranVoucher;
    // End of variables declaration//GEN-END:variables
}
