/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.user.dialog;

import com.common.ComponentUtil;
import com.common.Global;
import com.common.ProUtil;
import com.common.SelectionObserver;
import com.common.Util1;
import com.user.model.PropertyKey;
import com.user.model.SysProperty;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Lenovo
 */
public class ReportNameDialog extends javax.swing.JDialog {

    private SelectionObserver observer;

    public void setObserver(SelectionObserver observer) {
        this.observer = observer;
    }

    private final ActionListener action = (ActionEvent e) -> {
        if (e.getSource() instanceof JCheckBox chk) {
            String key = chk.getName();
            String value = Util1.getString(chk.isSelected());
            SysProperty p = new SysProperty();
            PropertyKey pKey = new PropertyKey();
            pKey.setPropKey(key);
            p.setKey(pKey);
            p.setPropValue(value);
            save(p);
        }
        if (e.getSource() instanceof JTextField txt) {
            String key = txt.getName();
            String value = txt.getText();
            SysProperty p = new SysProperty();
            PropertyKey pKey = new PropertyKey();
            pKey.setPropKey(key);
            p.setKey(pKey);
            p.setPropValue(value);
            save(p);
        }
    };

    /**
     * Creates new form ReportNameDialog
     *
     * @param frame
     */
    public ReportNameDialog(JFrame frame) {
        super(frame, false);
        initComponents();
        initTextBox();
        addActionListener(panelInv);
        addActionListener(panelAcc);
    }

    private void addActionListener(JPanel panel) {
        for (Component component : panel.getComponents()) {
            if (component instanceof JTextField txt) {
                txt.addActionListener(action);
            } else if (component instanceof JCheckBox txt) {
                txt.addActionListener(action);
            } else if (component instanceof JRadioButton txt) {
                txt.addActionListener(action);
            } else if (component instanceof JPanel p) {
                addActionListener(p);
            }
        }
    }

    private void initTextBox() {
        txtIOVoucher.setName(ProUtil.STOCK_IO_VOUCHER);
        txtTranVoucher.setName(ProUtil.TRANSFER_VOUCHER);
        txtPurVou.setName(ProUtil.PURCHASE_VOUCHER);
        txtDrCr.setName(ProUtil.DRCR_REPORT);
        txtSaleVou.setName(ProUtil.SALE_VOU);
        txtSaleA5.setName(ProUtil.SALE_VOU_A5);
        txtSaleA4.setName(ProUtil.SALE_VOU_A4);
        ComponentUtil.addFocusListener(this);
    }

    public void setData(HashMap<String, String> hmProperty) {
        txtIOVoucher.setText(hmProperty.get(txtIOVoucher.getName()));
        txtTranVoucher.setText(hmProperty.get(txtTranVoucher.getName()));
        txtPurVou.setText(hmProperty.get(txtPurVou.getName()));
        txtDrCr.setText(hmProperty.get(txtDrCr.getName()));
        txtSaleVou.setText(hmProperty.get(txtSaleVou.getName()));
        txtSaleA5.setText(hmProperty.get(txtSaleA5.getName()));
        txtSaleA4.setText(hmProperty.get(txtSaleA4.getName()));
    }

    private void save(SysProperty p) {
        int yn = JOptionPane.showConfirmDialog(this, "Are you sure to change setting?", "Setting", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (yn == JOptionPane.YES_OPTION) {
            observer.selected("save", p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInv = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPurVou = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtIOVoucher = new javax.swing.JTextField();
        txtTranVoucher = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSaleVou = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSaleA5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSaleA4 = new javax.swing.JTextField();
        panelAcc = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDrCr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelInv.setBorder(javax.swing.BorderFactory.createTitledBorder("Inventory"));

        jLabel2.setFont(Global.lableFont);
        jLabel2.setText("Stock I/O Voucher");

        txtPurVou.setFont(Global.textFont);

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("Transfer Voucher");

        txtIOVoucher.setFont(Global.textFont);

        txtTranVoucher.setFont(Global.textFont);

        jLabel3.setFont(Global.lableFont);
        jLabel3.setText("Purchase Voucher");

        jLabel5.setText("Sale Vou Report");

        txtSaleVou.setFont(Global.textFont);

        jLabel6.setText("Sale A5 Report");

        txtSaleA5.setFont(Global.textFont);

        jLabel7.setText("Sale A4 Report");

        txtSaleA4.setFont(Global.textFont);

        javax.swing.GroupLayout panelInvLayout = new javax.swing.GroupLayout(panelInv);
        panelInv.setLayout(panelInvLayout);
        panelInvLayout.setHorizontalGroup(
            panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSaleA4)
                    .addComponent(txtSaleA5)
                    .addComponent(txtSaleVou)
                    .addComponent(txtIOVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addComponent(txtTranVoucher)
                    .addComponent(txtPurVou, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panelInvLayout.setVerticalGroup(
            panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInvLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTranVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIOVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPurVou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSaleVou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtSaleA5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSaleA4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAcc.setBorder(javax.swing.BorderFactory.createTitledBorder("Account"));

        jLabel4.setFont(Global.lableFont);
        jLabel4.setText("Dr / Cr Voucher");

        txtDrCr.setFont(Global.textFont);

        javax.swing.GroupLayout panelAccLayout = new javax.swing.GroupLayout(panelAcc);
        panelAcc.setLayout(panelAccLayout);
        panelAccLayout.setHorizontalGroup(
            panelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDrCr, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );
        panelAccLayout.setVerticalGroup(
            panelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAccLayout.createSequentialGroup()
                .addGroup(panelAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDrCr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 183, Short.MAX_VALUE))
                    .addComponent(panelInv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel panelAcc;
    private javax.swing.JPanel panelInv;
    private javax.swing.JTextField txtDrCr;
    private javax.swing.JTextField txtIOVoucher;
    private javax.swing.JTextField txtPurVou;
    private javax.swing.JTextField txtSaleA4;
    private javax.swing.JTextField txtSaleA5;
    private javax.swing.JTextField txtSaleVou;
    private javax.swing.JTextField txtTranVoucher;
    // End of variables declaration//GEN-END:variables
}
