/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.user.dialog;

import com.common.Global;
import com.repo.UserRepo;
import com.user.editor.CompanyAutoCompleter;
import com.user.model.CompanyInfo;
import com.user.model.YearEnd;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import lombok.Setter;

/**
 *
 * @author Lenovo
 */
public class YearEndFixDialog extends javax.swing.JDialog {

    @Setter
    private UserRepo userRepo;
    @Setter
    private String token;
    private CompanyAutoCompleter yeCompleter;
    private CompanyAutoCompleter fixCompleter;

    /**
     * Creates new form YearEndProcessingDailog
     *
     * @param parent
     */
    public YearEndFixDialog(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
    }

    public void initMain() {
        yeCompleter = new CompanyAutoCompleter(txtYe, null);
        fixCompleter = new CompanyAutoCompleter(txtFix, null);
    }

    public void searchCompany() {
        userRepo.getCompany(true).doOnSuccess((t) -> {
            yeCompleter.setListCompany(t);
            fixCompleter.setListCompany(t);
        }).subscribe();
        setVisible(true);
    }

    private void confirm() {
        if (isValidEntry()) {
            int yn = JOptionPane.showConfirmDialog(this, "Are you sure to fix year end processing?"
                    + "", "Confirm Dialog", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE);
            if (yn == JOptionPane.YES_OPTION) {
                progress.setIndeterminate(true);
                lblLog.setText("Please wait this make a few minute...");
                btnConfirm.setEnabled(false);
                btnExit.setEnabled(false);
                String yeCompCode = yeCompleter.getCompany().getCompCode();
                String fixCompCode = fixCompleter.getCompany().getCompCode();
                YearEnd end = new YearEnd();
                end.setYeCompCode(yeCompCode);
                end.setCompCode(fixCompCode);
                end.setToken(token);
                userRepo.yearEndFix(end).doOnSuccess((t) -> {
                    lblLog.setText(t.getMessage());
                    String compCode = t.getCompCode();
                    if (compCode != null) {
                        lblLog.setText(t.getMessage());
                        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
                        btnConfirm.setEnabled(true);
                        btnExit.setEnabled(true);
                        progress.setIndeterminate(false);
                        dispose();
                    }
                }).doOnError((e) -> {
                    error(e);
                }).subscribe();
            }
        }
    }

    private void error(Throwable e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
        setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        progress.setIndeterminate(false);
        btnConfirm.setEnabled(true);
        btnExit.setEnabled(true);
    }

    private boolean isValidEntry() {
        CompanyInfo c1 = yeCompleter.getCompany();
        CompanyInfo c2 = fixCompleter.getCompany();
        if (c1 == null) {
            JOptionPane.showMessageDialog(this, "Invalid Year End Company.");
            txtYe.requestFocus();
            return false;
        } else if (c2 == null) {
            JOptionPane.showMessageDialog(this, "Invalid Fix Company.");
            txtFix.requestFocus();
            return false;
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnConfirm = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtYe = new javax.swing.JTextField();
        txtFix = new javax.swing.JTextField();
        lblLog = new javax.swing.JLabel();

        setTitle("Year End Dialog");

        jLabel1.setFont(Global.lableFont);
        jLabel1.setText("Year End Company");

        btnConfirm.setFont(Global.lableFont);
        btnConfirm.setText("Confirm");
        btnConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(Global.menuFont);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Year End Fix");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel5.setFont(Global.lableFont);
        jLabel5.setText("Fix Company");

        btnExit.setFont(Global.lableFont);
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblLog.setFont(Global.lableFont);
        lblLog.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnConfirm))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtYe)
                                    .addComponent(txtFix, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(progress, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirm)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmActionPerformed
        // TODO add your handling code here:
        confirm();
    }//GEN-LAST:event_btnConfirmActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirm;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLog;
    private javax.swing.JProgressBar progress;
    private javax.swing.JTextField txtFix;
    private javax.swing.JTextField txtYe;
    // End of variables declaration//GEN-END:variables

}
