/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.inventory.ui.entry.dialog;

import com.common.Global;
import com.common.Util1;
import com.inventory.model.MillingOutDetail;
import com.inventory.model.MillingUsage;
import com.inventory.ui.common.MilingOutTableModel;
import com.inventory.ui.entry.dialog.common.MillingUsageTableModel;
import com.repo.InventoryRepo;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Lenovo
 */
public class MillingUsageDialog extends javax.swing.JDialog {

    private MillingUsageTableModel millingUsageTableModel = new MillingUsageTableModel();
    private InventoryRepo inventoryRepo;
    private MilingOutTableModel millingOutTableModel;
    private boolean confirm = false;

    public boolean isConfirm() {
        return confirm;
    }

    public void setConfirm(boolean confirm) {
        this.confirm = confirm;
    }

    public void setInventoryRepo(InventoryRepo inventoryRepo) {
        this.inventoryRepo = inventoryRepo;
    }

    public void setMilingOutTableModel(MilingOutTableModel millingOutTableModel) {
        this.millingOutTableModel = millingOutTableModel;
    }

    /**
     * Creates new form MillingUsageDialog
     *
     * @param frame
     */
    public MillingUsageDialog(JFrame frame) {
        super(frame, true);
        initComponents();
    }

    public void initMain() {
        initTable();
    }

    private void initTable() {
        millingUsageTableModel.setTable(tblUsage);
        millingUsageTableModel.setInventoryRepo(inventoryRepo);
        tblUsage.setCellSelectionEnabled(true);
        tblUsage.setModel(millingUsageTableModel);
        tblUsage.getTableHeader().setFont(Global.tblHeaderFont);
        tblUsage.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsage.setFont(Global.textFont);
        tblUsage.setRowHeight(Global.tblRowHeight);
        tblUsage.setShowGrid(true);
        tblUsage.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT)
                .put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0), "selectNextColumnCell");
        tblUsage.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblUsage.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblUsage.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblUsage.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblUsage.getColumnModel().getColumn(3).setPreferredWidth(40);
    }

    public void search(String vouNo) {
        if (Util1.isNullOrEmpty(vouNo)) {
            List<MillingOutDetail> list = millingOutTableModel.getListDetail();
            if (list != null) {
                millingUsageTableModel.clear();
                list.forEach((t) -> {
                    String stockCode = t.getStockCode();
                    if (!Util1.isNullOrEmpty(stockCode)) {
                        double qty = t.getQty();
                        inventoryRepo.getPattern(stockCode, null).doOnSuccess((listPattern) -> {
                            if (listPattern != null) {
                                listPattern.forEach((p) -> {
                                    MillingUsage u = new MillingUsage();
                                    u.setUserCode(u.getUserCode());
                                    u.setStockCode(p.getKey().getStockCode());
                                    u.setStockName(p.getStockName());
                                    u.setQty(qty * p.getQty());
                                    u.setUnit(p.getUnitCode());
                                    u.setLocCode(p.getLocCode());
                                    u.setLocName(p.getLocName());
                                    millingUsageTableModel.addObject(u);
                                });
                            }
                        }).doOnTerminate(() -> {
                            setVisible(true);
                        }).subscribe();
                    }
                });
            }
        }
    }

    public List<MillingUsage> getListUsage() {
        return millingUsageTableModel.getListDetail();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsage = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Milling Usage Stock Dialog");

        tblUsage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblUsage);

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setConfirm(false);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setConfirm(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsage;
    // End of variables declaration//GEN-END:variables
}
