/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.acc.dialog;

import com.common.ComponentUtil;
import com.common.Global;
import com.common.IconUtil;
import com.common.StartWithRowFilter;
import com.formdev.flatlaf.FlatClientProperties;
import java.awt.Dialog;
import java.awt.event.KeyEvent;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Lenovo
 */
@Slf4j
public class FindDialog extends javax.swing.JDialog {

    private TableRowSorter<TableModel> sorter;
    private StartWithRowFilter swrf;
    private JTable[] tables;

    /**
     * Creates new form FindDialog
     *
     * @param frame
     * @param tables
     */
    public FindDialog(JFrame frame, JTable... tables) {
        super(frame, Dialog.ModalityType.MODELESS);
        super.setIconImage(IconUtil.getImage(IconUtil.SEARCH_ICON));
        this.tables = tables;
        setLocationRelativeTo(null);
        initComponents();
        initFoucs();
        initRowFilter();
        initClientProperty();
    }

    private void initFoucs() {
        ComponentUtil.addFocusListener(this);
    }

    private void initRowFilter() {
        for (JTable table : tables) {
            sorter = new TableRowSorter<>(table.getModel());
            table.setRowSorter(sorter);
            swrf = new StartWithRowFilter(txtSearch);
        }

    }

    private void initClientProperty() {
        txtSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        txtSearch.putClientProperty(FlatClientProperties.TEXT_FIELD_LEADING_ICON, IconUtil.getIcon(IconUtil.SEARCH_ICON, 0.9f));
    }

//    private void find() {
//
//        SwingUtilities.invokeLater(() -> {
//            log.info("search.");
//            if (txtSearch.getText().isEmpty()) {
//                sorter.setRowFilter(null);
//            } else {
//                sorter.setRowFilter(swrf);
//            }
//        });
//    }
    private void find() {
        SwingUtilities.invokeLater(() -> {
            if (txtSearch.getText().isEmpty()) {
                for (JTable table : tables) {
                    sorter = (TableRowSorter<TableModel>) table.getRowSorter();
                    sorter.setRowFilter(null);
                }
            } else {
                for (JTable table : tables) {
                    sorter = (TableRowSorter<TableModel>) table.getRowSorter();
                    sorter.setRowFilter(swrf);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();

        setTitle("Find");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jLabel1.setText("Find What :");

        txtSearch.setFont(Global.textFont);
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ESCAPE) {
            setVisible(false);
        }
        find();
    }//GEN-LAST:event_txtSearchKeyReleased

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusLost

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

}
